--PART A
SELECT * FROM PERSON
SELECT * FROM DEPARTMENT

--1.
SELECT * FROM PERSON P
CROSS JOIN DEPARTMENT D

SELECT * FROM PERSON,DEPARTMENT
--2.
SELECT PERSONNAME,DEPARTMENTNAME FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
--3.
SELECT PERSONNAME,DEPARTMENTNAME,DEPARTMENTCODE FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
--4.
SELECT PERSONNAME,DEPARTMENTCODE,LOCATION FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
--5.
SELECT * FROM PERSON P 
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DEPARTMENTNAME = 'MECHANICAL'
--6.
SELECT PERSONNAME,DEPARTMENTCODE,SALARY FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE CITY = 'AHMEDABAD'
--7.
SELECT PERSONNAME FROM PERSON P 
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE LOCATION = 'C-BLOCK'
--8.
SELECT PERSONNAME,SALARY,DEPARTMENTNAME FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE CITY = 'JAMNAGAR'
--9.
SELECT * FROM PERSON P 
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DEPARTMENTNAME = 'CIVIL' AND JOININGDATE > '01-08-2001'
--10.
SELECT PERSONNAME,DEPARTMENTNAME FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DATEDIFF(YEAR,P.JOININGDATE,GETDATE()) > 25
--11.
SELECT DEPARTMENTNAME,COUNT(P.PERSONID) [PEROSN COUNT] FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
--12.
SELECT DEPARTMENTNAME ,MAX(P.SALARY) [MAXMIMUM] ,MIN(P.SALARY) [MINIMUM] FROM DEPARTMENT D
RIGHT JOIN PERSON P
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
--13.
SELECT DEPARTMENTNAME ,MAX(P.SALARY) [MAXMIMUM] ,MIN(P.SALARY) [MINIMUM] ,SUM(P.SALARY) [TOTAL] , AVG(P.SALARY) [AVG]FROM DEPARTMENT D
RIGHT JOIN PERSON P
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
--14.
SELECT CITY, AVG(P.SALARY) [AVGSALARY] FROM PERSON P 
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE CITY = 'AHMEDABAD'
GROUP BY CITY
--15.
SELECT CONCAT(PERSONNAME,' LIVES IN ',CITY,' AND WORKS IN ',DEPARTMENTNAME) [PERSON DETAIL] FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
--PART B
--16.
SELECT CONCAT(PERSONNAME,' EARNS ',SALARY,' FROM ',DEPARTMENTNAME,' DEPARTMENT MONTHLY') [PERSON DETAIL] FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
--17.
SELECT CITY,DEPARTMENTNAME, SUM(P.SALARY) [TOTAL] ,AVG(P.SALARY) [AVG] ,MAX(P.SALARY) [MAXIMUM]  FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY CITY,DEPARTMENTNAME
--18.
SELECT PERSONNAME FROM PERSON P 
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DEPARTMENTNAME IS NULL
--19.
SELECT DEPARTMENTNAME, SUM(P.SALARY) [TOTAL] FROM PERSON P 
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING SUM(P.SALARY) > 100000
--PART C

--20.
SELECT DEPARTMENTNAME FROM PERSON P 
RIGHT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE PERSONID IS NULL
GROUP BY DEPARTMENTNAME

--21.
SELECT DEPARTMENTNAME FROM PERSON P 
RIGHT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING COUNT(P.DEPARTMENTID) > 2

--22.
UPDATE PERSON
SET SALARY = SALARY* 1.10
FROM DEPARTMENT
WHERE PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
AND DEPARTMENT.DEPARTMENTNAME = 'COMPUTER'

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT