--PART-A
SELECT * FROM DEPOSITE
SELECT * FROM EMPLOYE
SELECT * FROM STUDENT
--1.
SELECT * INTO HIGH_AMOUNT
FROM DEPOSITE WHERE AMOUNT>3000;
--2.
SELECT CNAME, AMOUNT INTO MAVDI_CUSTOMER
FROM DEPOSITE WHERE BNAME='MAVDI';
--3.
SELECT * INTO RESENT_DEPOSIT
FROM DEPOSITE WHERE ADATE>'01-01-2025'
--4.
SELECT DISTINCT BNAME INTO BRANCH_LIST
FROM DEPOSITE;
--5.
SELECT TOP 5 * INTO TOP_DEPOSITES
FROM DEPOSITE;
--6.
SELECT * INTO MID_RANGE
FROM DEPOSITE WHERE AMOUNT BETWEEN 2000 AND 6000;
--7.
SELECT DISTINCT BNAME INTO UNIQUE_BRANCH
FROM DEPOSITE;
--8.
SELECT * INTO NO_BRANCH_ASSIGNED
FROM DEPOSITE WHERE BNAME IS NULL;
--9.
SELECT ACTNO,CNAME,BNAME,AMOUNT AS BALANCE,ADATE INTO DEPOSITE_COPY
FROM DEPOSITE
--10.
SELECT * INTO SELECTED_BRANCH
FROM DEPOSITE WHERE BNAME IN ('MAVDI','BEDI');
--11.
SELECT ACTNO,CNAME,BNAME,AMOUNT,ADATE INTO STUDENT_BACKUP FROM DEPOSITE
WHERE 1=0;
--12.
SELECT FIRSTNAME,CITY INTO CS_STUDENT
FROM EMPLOYE WHERE DEPARTMENT='COMPUTER';
--13.
SELECT TOP 3 SPI INTO TOPER_LIST
FROM STUDENT;
--14.
SELECT DISTINCT CITY INTO CITY_LIST
FROM STUDENT;
--15.
SELECT * INTO MID_STUDENT
FROM STUDENT
WHERE STDID BETWEEN 103 AND 108;
--16.
SELECT * INTO NULL_BRANCH
FROM STUDENT WHERE BRANCH IS NULL;
--17.
SELECT SPI AS PERFOMENCE INTO STUDENT_COPY
FROM STUDENT
--18.
SELECT * INTO CITY_WISE
FROM STUDENT
WHERE CITY IN ('RAJKOT','SURAT');
--19.
SELECT * INTO NON_CIVIL
FROM STUDENT
WHERE BRANCH <> 'CIVIL';
--20.
SELECT SNAME,CITY INTO NEW
FROM STUDENT