--PART - A
SELECT * FROM BANK_DEPOSIT;
--1.
ALTER TABLE  DEPOSITE
ADD STATES VARCHAR(20);
--2.
ALTER TABLE DEPOSITE
ADD CITY VARCHAR(20),PINCODE INT;
--3.
ALTER TABLE DEPOSITE
ALTER COLUMN CITY VARCHAR(20);
--4.
ALTER TABLE DEPOSITE
ALTER COLUMN AMOUNT INT
--5.
ALTER TABLE DEPOSITE
DROP COLUMN CITY;
--6.
SP_RENAME 'DEPOSITE.ACTNO','ANO';
--7.
SP_RENAME 'DEPOSITE.BANME','BRANCH_NAME'
--8.
SP_RENAME 'DEPOSITE','DEPOSIT_DETAILS'
--9.
ALTER TABLE DEPOSITE
ADD IFSC_CODE VARCHAR(15);
--10.
ALTER TABLE DEPOSITE
ALTER COLUMN BANME VARCHAR(30);
--PART - B
--11.
SP_RENAME 'DEPOSITE.ADATE','AOPENDATE'
--12.
ALTER TABLE DEPOSIT_DETAILS
DROP COLUMN AOPENDATE
--13.
SP_RENAME 'DEPOSIT_DETAILS.CNAME','CUSTOMER_NAME'
--14.
ALTER TABLE DEPOSIT_DETAILS
ADD COUNTRY VARCHAR(20);
--15.
ALTER TABLE DEPOSIT_DETAILS
ADD ACCOUNT_TYPE VARCHAR(15);

--PART-C
--16.
ALTER TABLE DEPOSIT_DETAILS
ALTER COLUMN PINCODE BIGINT
--17.
ALTER TABLE DEPOSIT_DETAILS
DROP COLUMN ACCOUNT_TYPE
--18.
SP_RENAME 'DEPOSIT_DETAILS.AMOUNT','BALANCE'
--19.
ALTER TABLE DEPOSIT_DETAILS
ADD STATUS VARCHAR(10);
--20.
SP_RENAME 'DEPOSIT_DETAILS','BANK_DEPOSIT'

-- PART-A
SELECT * FROM BANK_DEPOSIT;
--1.
DELETE FROM BANK_DEPOSIT
WHERE BALANCE<3000;
--2.
DELETE FROM BANK_DEPOSIT
WHERE BRANCH_NAME = 'BEDI';
--3.
DELETE FROM BANK_DEPOSIT
WHERE ANO > 102 AND ANO < 109
--4.
DELETE FROM BANK_DEPOSIT
WHERE BRANCH_NAME = 'BEDI' OR BRANCH_NAME = 'MADHAPAR';
--5.
--DELETE FROM BANK_DEPOSIT
--WHERE BALANCE = 8000 AND ADATE > '1-1-2025';
--6.
DELETE FROM BANK_DEPOSIT 
WHERE BRANCH_NAME IS NULL
--7.
DELETE FROM BANK_DEPOSIT
WHERE BALANCE = 7000 AND BNAME = 'CHARMI' AND BRANCH_NAME='SHITAL PARK';
--8.
DELETE FROM BANK_DEPOSITE;
--9.
TRUNCATE TABLE BANK_DEPOSITE;
--10.
DROP TABLE BANK_DEPOSITE;
--PART-B
--11.
DELETE FROM STUDENT 
WHERE STDID > 105 
--12.
DELETE FROM STUDENT
WHERE BRANCH IS NULL AND SNAME IS NOT NULL
--13.
DELETE FROM STUDENT 
WHERE SPI<9 AND CITY = 'RAJKOT'
--14.
DELETE FROM STUDENT
WHERE BRANCH IS NOT NULL;
--15.
TRUNCATE TABLE STUDENT;