SELECT * FROM STUDENT;
SELECT * FROM EMPLOYE;
SELECT * FROM DEPOSITE;
--1.
SELECT * FROM EMPLOYE 
WHERE FIRSTNAME LIKE 'H%';
--2.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '_____';
--3.
SELECT * FROM EMPLOYE
WHERE CITY LIKE '_____T';
--4.
SELECT * FROM EMPLOYE
WHERE LASTNAME LIKE '%EL';
--5.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE 'R%A';
--6.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE 'V_S%'
--7.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '______' AND CITY IS NULL;
--8.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '%AR%'
--9.
SELECT * FROM EMPLOYE
WHERE CITY LIKE '[RB]%';
--10.
SELECT * FROM EMPLOYE
WHERE DEPARTMENT IS NOT NULL;
--11.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '[A-H]%'
--12.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '_[A,E,I,O,U]%'
--13.
SELECT * FROM EMPLOYE
WHERE LEN(FIRSTNAME)>5;
--14.
SELECT * FROM EMPLOYE
WHERE LASTNAME LIKE 'PA%';
--15.
SELECT * FROM EMPLOYE
WHERE CITY NOT LIKE 'B%';
--16.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME NOT LIKE '_[A,E,I,O,U]%'
--17.
SELECT * FROM EMPLOYE
WHERE JOININGYEAR LIKE '___[4,6]'
--18.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE 'H%I' AND CITY LIKE '%RA%'
--19.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '%A%' AND CITY LIKE '%D' AND DEPARTMENT IS NOT NULL;
--20.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '_[AEIOU][AEIOU]' AND CITY LIKE 'R%'
--21.
SELECT FIRSTNAME FROM EMPLOYE
WHERE CITY LIKE '%RA%' AND SALARY < 13000 AND JOININGYEAR LIKE '___6'
--22.
SELECT * FROM EMPLOYE
WHERE SALARY BETWEEN 10000 AND 15000 AND CITY LIKE '%KO%' AND FIRSTNAME LIKE 'H%';
--23.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '[AD]%' AND SALARY > 12000;
--24.
SELECT * FROM EMPLOYE
WHERE CITY LIKE '%N%' AND SALARY<15000
--25.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '______' AND CITY LIKE '%AR';
--26.
SELECT FIRSTNAME FROM EMPLOYE
WHERE FIRSTNAME LIKE '%[AEIOU]'
AND DEPARTMENT LIKE '[AEIOU]%'
AND SALARY BETWEEN 10000 AND 15000;
--27.
SELECT * FROM EMPLOYE
WHERE LASTNAME LIKE '%A%' AND GENDER = 'MALE'
AND SALARY <> 14000;
--28.
SELECT * FROM EMPLOYE
WHERE FIRSTNAME LIKE '[_AEIOU]' AND LASTNAME LIKE '%R'
AND SALARY < 12000;
--29.
SELECT * FROM EMPLOYE
WHERE CITY IS NOT NULL AND
FIRSTNAME LIKE '^[AEIOU]%'
AND DEPARTMENT NOT IN ('HR','IT');
--30.
SELECT * FROM EMPLOYE
WHERE CITY IS NOT NULL AND
FIRSTNAME LIKE '%[AEIOU]'
AND DEPARTMENT NOT IN ('HR','IT');