--1.
SELECT * FROM STUDENT
--2.
SELECT SNAME,CITY FROM STUDENT
--3.
SELECT * FROM STUDENT WHERE BRANCH = 'COMPUTER'
--4.
SELECT * FROM STUDENT WHERE STDID < 105
--5.
SELECT SNAME,CITY,SPI FROM STUDENT WHERE SPI > 6.60
--6.
SELECT SNAME FROM STUDENT WHERE BRANCH = 'COMPUTER' AND SPI > 8
--7.
SELECT SNAME FROM STUDENT WHERE STDID>103 AND CITY = 'RAJKOT'
--8.
SELECT SNAME FROM STUDENT WHERE CITY = 'RAJKOT' OR CITY = 'SURAT'
SELECT SNAME FROM STUDENT WHERE CITY IN ('RAJKOT','SURAT')
--9.
SELECT SNAME FROM STUDENT WHERE  SPI>8 AND STDID<105
--10.
SELECT * FROM STUDENT WHERE SPI > 7 AND SPI < 9;
SELECT * FROM STUDENT WHERE SPI BETWEEN 7 AND 9; 
--11.
SELECT * FROM STUDENT WHERE BRANCH <> 'COMPUTER'
--12.
SELECT STDID,SNAME,SPI FROM STUDENT WHERE BRANCH = 'COMPUTER' OR BRANCH = 'CE' OR BRANCH = 'COMPUTER' AND STDID<104
--13.
SELECT STDID,SNAME FROM STUDENT WHERE BRANCH NOT IN('COMPUTER','CIVIL')
--14.
SELECT SNAME FROM STUDENT WHERE SNAME <> 'DEEP'
--15.
SELECT SNAME FROM STUDENT WHERE BRANCH = NULL
--16.
SELECT DISTINCT * FROM STUDENT
--17.
SELECT TOP 50 PERCENT * FROM STUDENT
--18.
SELECT TOP 5 STDID FROM STUDENT
--19.
SELECT TOP 5 * FROM STUDENT
--20.
SELECT TOP 3 * FROM STUDENT WHERE SPI > 8
--21.
SELECT TOP 5 SNAME,STDID FROM STUDENT WHERE BRANCH <> 'COMPUTER'
--22.
SELECT STDID FROM STUDENT WHERE STDID NOT IN (105,109)
--23.
SELECT * FROM STUDENT WHERE SPI>7 OR SPI<9 AND STDID BETWEEN 102 AND 108
--24.
SELECT STDID,SNAME,CITY,SPI,BRANCH FROM STUDENT WHERE SPI > 8
--25.
SELECT SNAME FROM STUDENT WHERE CITY = 'RAJKOT' AND SPI < 8
--26.
SELECT * FROM STUDENT WHERE SPI > 8 AND STDID < 105
--27
SELECT * FROM STUDENT WHERE SPI > 7.5 AND STDID BETWEEN 100 AND 110 AND CITY = 'RAJKOT' OR CITY = 'SURAT'
--28.
SELECT * FROM STUDENT WHERE BRANCH = 'CIVIL' OR BRANCH = 'MECHANIAL' AND SPI > 8