SELECT * FROM EMPLOYE
--1.
SELECT MAX(SALARY) AS 'MAXIMUM SALARY',MIN(SALARY) AS 'MINIMUM SALARY' FROM EMPLOYE 
--2.
SELECT SUM(SALARY) AS 'TOTAL SALARY',AVG(SALARY) AS 'AVERAGE SALARY' FROM EMPLOYE
--3.
SELECT COUNT(EID) AS 'TOTAL MEMBER' FROM EMPLOYE
--4.
SELECT MAX(SALARY) FROM EMPLOYE
WHERE CITY = 'RAJKOT';
--5.
SELECT MAX(SALARY) FROM EMPLOYE
WHERE DEPARTMENT = 'IT';
--6.
SELECT COUNT(EID) FROM EMPLOYE
WHERE DEPARTMENT = 'HR';
--7.
SELECT AVG(SALARY) FROM EMPLOYE
WHERE DEPARTMENT = 'ADMIN';
--8.
SELECT SUM(SALARY) FROM EMPLOYE
WHERE DEPARTMENT = 'HR';
--9.
SELECT COUNT(DISTINCT CITY) FROM EMPLOYE
--10.
SELECT COUNT(DISTINCT DEPARTMENT) FROM EMPLOYE
--11.
SELECT MIN(SALARY) FROM EMPLOYE
WHERE CITY = 'AHMEDABAD';
--12.
SELECT MAX(SALARY) FROM EMPLOYE
GROUP BY CITY;
--13.
SELECT MIN(SALARY) FROM EMPLOYE
GROUP BY DEPARTMENT;
--14.
SELECT MIN(SALARY) FROM EMPLOYE
GROUP BY CITY;
--15.
SELECT AVG(SALARY) FROM EMPLOYE
WHERE CITY = 'SURAT';
--16.
SELECT SUM(SALARY) FROM EMPLOYE
WHERE GENDER = 'FEMALE';
--17.
SELECT COUNT(EID) FROM EMPLOYE
WHERE GENDER = 'MALE';
--18.
SELECT CITY,COUNT(EID) FROM EMPLOYE
GROUP BY CITY;
--19.
SELECT CITY, COUNT(EID) FROM EMPLOYE
WHERE GENDER = 'MALE'
GROUP BY CITY
--20.
SELECT DEPARTMENT,MAX(SALARY) FROM EMPLOYE
WHERE CITY <> 'AHMEDABAD'
GROUP BY DEPARTMENT;
--21.
SELECT CITY ,MIN(SALARY) FROM EMPLOYE
WHERE GENDER = 'FEMALE'
GROUP BY CITY;
--22.
SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYE
GROUP BY DEPARTMENT;
--23.
SELECT AVG(SALARY) FROM EMPLOYE GROUP BY DEPARTMENT;
--24.
SELECT COUNT(EID) FROM EMPLOYE GROUP BY DEPARTMENT,CITY;
--25.
SELECT GENDER, SUM(SALARY) FROM EMPLOYE
GROUP BY GENDER
--26.
SELECT CITY,MAX(SALARY), MIN(SALARY) FROM EMPLOYE
GROUP BY CITY;
--27.
SELECT AVG(SALARY) FROM EMPLOYE
GROUP BY DEPARTMENT,SALARY,GENDER;
--28.
SELECT (MAX(SALARY) - MIN(SALARY)) AS DIFFRENCE FROM EMPLOYE
--29.
SELECT SUM(SALARY) FROM EMPLOYE
WHERE DEPARTMENT LIKE '_____'
GROUP BY DEPARTMENT 
--30.
SELECT MAX(SALARY) FROM EMPLOYE
WHERE CITY LIKE 'R%'
GROUP BY DEPARTMENT,CITY 