--SHOW
SELECT * FROM STUDENT;
--1.
UPDATE STUDENT
SET SPI = 8;
--2.
UPDATE STUDENT
SET CITY='AHMEDABAD'
WHERE SNAME = 'HETVI'
--3.
UPDATE STUDENT
SET SPI = 9.20,CITY = 'VADODARA'
WHERE SNAME = 'DEEP'
--4.
UPDATE STUDENT
SET SPI = 8.50
WHERE SNAME = 'DHARMIK'
--5.
UPDATE STUDENT
SET BRANCH='IT'
WHERE BRANCH = 'COMPUTER'
--6.
UPDATE STUDENT
SET BRANCH = 'AUTOMOBILE'
WHERE SNAME = 'RAJ'
--7.
UPDATE STUDENT
SET SPI = 7.50
WHERE STDID BETWEEN 103 AND 107
--8.
UPDATE STUDENT
SET CITY = 'MUMBAI'
WHERE SNAME = 'PARAG'
--9.
UPDATE STUDENT
SET SPI = 6.00
WHERE SNAME = 'RIYA'
--10.
UPDATE STUDENT
SET SPI = 7.20
WHERE BRANCH = 'ELECTRICAL'
--11.
UPDATE STUDENT
SET SPI = SPI * 1.10
--12.
UPDATE STUDENT
SET SPI = SPI * 1.20
--13.
UPDATE STUDENT
SET SPI = SPI * 0.50
--14.
UPDATE STUDENT
SET BRANCH = 'EC',SPI = 8,CITY='SURAT'
WHERE SNAME = 'KRUNAL'
--15.
UPDATE STUDENT
SET CITY = 'RAJKOT',SPI=7
WHERE BRANCH = 'CIVIL' AND STDID < 105
--16.
UPDATE STUDENT
SET SPI = NULL
WHERE STDID=110
--17.
UPDATE STUDENT
SET BRANCH = NULL
WHERE SNAME = 'VISHAL'
--18.
SELECT SNAME FROM STUDENT WHERE SPI IS NULL
--19.
SELECT SNAME FROM STUDENT WHERE BRANCH IS NOT NULL
--20.
UPDATE STUDENT
SET STDID = 108,SNAME='DARSHAN'
WHERE BRANCH = 'COMPUTER' AND SPI = 8.50
--21.
UPDATE STUDENT
SET CITY = 'SURAT'
WHERE SPI < 7;
--22.
UPDATE STUDENT
SET CITY = NULL,BRANCH='MECHANICAL'
WHERE STDID = 109;